[package]
name = "webauthn-rs"
version = "0.3.0-alpha.1"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"
build = "build.rs"

description = "Webauthn Framework for Rust Web Servers"
# documentation = "..."
# homepage = "..."
repository = "https://github.com/kanidm/webauthn-rs"
readme = "README.md"
keywords = ["webauthn", "authentication"]
categories = ["authentication", "web-programming"]
license = "MPL-2.0"

[dependencies]
base64 = "0.12"
log = "0.4"
nom = "4.2"
serde = "1.0"
serde_bytes = "0.11"
serde_cbor = "0.11"
serde_derive = "1.0"
serde_json = "1.0"
# We could consider replacing this with openssl rand.
openssl = "0.10"
rand = "0.7"
thiserror = "1.0"

[dev-dependencies]
askama = "0.10"

# This only supports up to 0.7. See examples/actix/main.rs for more.
actix = "0.10"
actix-web = { version = "2.0", features = ["openssl"] }
actix-session = "0.3"
actix-files = "0.2"

# Example, use the version numbers you need
tide = "0.15.0"
tide-rustls = "0.1.3"
askama_tide = "0.12.0"
async-std = { version = "1.6.0", features = ["attributes"] }
xactor = "0.7.8"
async-trait = "0.1.42"

# cookie = "0.11"
log = "0.4"
env_logger = "0.7"
futures = "0.3"
time = "0.2"
openssl = "0.10"

lru = "0.6"

structopt = { version = "0.3", default-features = false }

