[package]
name = "webauthn-rs"
version = "0.3.0-alpha.1"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"
build = "build.rs"

description = "Webauthn Framework for Rust Web Servers"
# documentation = "..."
# homepage = "..."
repository = "https://github.com/kanidm/webauthn-rs"
readme = "README.md"
keywords = ["webauthn", "authentication"]
categories = ["authentication", "web-programming"]
license = "MPL-2.0"

[dependencies]
base64 = "0.12"
log = "0.4"
nom = "4.2"
serde = "1.0"
serde_bytes = "0.11"
serde_cbor = "0.11"
serde_derive = "1.0"
serde_json = "1.0"
# We could consider replacing this with openssl rand.
openssl = "0.10"
rand = "0.7"
thiserror = "1.0"

[dev-dependencies]
actix-web = { version = "3", features = ["rustls"] }
actix-files = "0.4"

# cookie = "0.11"
log = "0.4"
env_logger = "0.7"
thiserror = "1.0"
dotenv = "0.15.0"

